name: movie_tracker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.7+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  majestica_ds:
    git:
      url: https://github.com/Majestica-Dev/design-system.git
      ref: main

  auto_route: ^9.2.1+1
  chat_gpt_sdk: ^3.1.0
  dio: ^5.6.0
  drift: ^2.20.0
  drift_dev: ^2.20.1
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  injectable: ^2.4.4
  path: ^1.9.0
  path_provider: ^2.1.4
  fpdart: ^1.1.0
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  lottie: ^3.1.2
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  open_apps_settings: ^0.0.4
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  uuid: ^4.4.2
  sentry_flutter: ^8.7.0
  in_app_review: ^2.0.9
  intl: ^0.19.0
  rxdart: ^0.28.0
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  mccounting_text: ^1.0.0
  flutter_native_splash: ^2.4.1
  purchases_flutter: ^8.1.0
  flutter_app_badge: ^2.0.2
  amplitude_flutter: ^3.7.0
  store_checker: ^1.6.0
  firebase_core: ^3.5.0
  firebase_analytics: ^11.3.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1
  freezed: ^2.5.7

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/lotties/
    - assets/intro/
    - assets/icons/
    - assets/onboarding/
    - assets/onboarding/icons/
    - assets/onboarding/images/
    - assets/icons/spike/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
    - family: New-York
      fonts:
        - asset: assets/fonts/NewYorkLarge-Regular.otf

flutter_native_splash:
  image: assets/icons/app_icon.png
  color: "#6B66DA"
