name: movie_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  majestica_ds:
    git:
      url: https://github.com/Majestica-Dev/design-system.git
      ref: main

  auto_route: ^9.2.1+1
  chat_gpt_sdk: ^3.1.0
  dio: ^5.6.0
  drift: ^2.20.0
  drift_dev: ^2.20.1
  envied: ^0.5.4+1
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  injectable: ^2.4.4
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.4
  fpdart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1
  freezed: ^2.5.7

flutter:
  generate: true
  uses-material-design: true
